<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SunoScrapper</AssemblyName>
    <RootNamespace>SunoScrapper</RootNamespace>
    <ApplicationIcon>scrapper.ico</ApplicationIcon>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="scrapper.ico"/>
    <Resource Include="scrapper.png"/>
  </ItemGroup>
</Project>

